name: Publish
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Submodule
        run: bash submodule.sh
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Index
        run: npx -y pagefind --site .vitepress/dist
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./.vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

